
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
/* tslint:disable */
import '@tailwindcss/browser';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { GoogleGenAI } from '@google/genai';
import App from './App';

// Polyfill process.env for scripts generated by the LLM that may reference it directly.
// Also expose GoogleGenAI globally for simple script initialization inside generated HTML.
(window as any).process = {
  env: {
    API_KEY: process.env.API_KEY
  }
};
(window as any).GoogleGenAI = GoogleGenAI;

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error('Could not find root element to mount to');
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
